### ISSUE TITLE
Unclear if only for ST2 or ST2+ST3

### ISSUE THREAD

**Issue by sandebert** [jarod2d/sublime_valign#35]
The readme states "for Sublime Text 2", yet it's tagged as for both ST2 and ST3 [at Package Control](https://packagecontrol.io/packages/VAlign). It would probably be beneficial to clarify which it is.

**Comment by jarod2d** [comment]
Thanks for the heads up! I've updated the readme and GitHub project to reflect that the plugin supports Sublime Text 2 and 3.
