### ISSUE TITLE
es6 imports alignment

### ISSUE THREAD

**Issue by satazor** [jarod2d/sublime_valign#39]
I usually align my nodejs require calls like this, which VAlign supports out of the box.

```js
var fs   = require('fs');
var path = require('path');
```

I'm not experimenting with es6 imports but VAlign doesn't seem to understand them:

```js
import { Component }     from 'react';
import { TodoListItem }  from './TodoListItem';
```

I would like to have this working out of the box. Thoughts?

**Comment by jarod2d** [comment]
This kind of alignment requires more complex logic than what VAlign currently offers. VAlign knows how to locate a substring (like "=" or ":") to align on and then locate the same substring in surrounding lines to perform the alignment.

To do this properly, the plugin would need a greater understanding of the semantics of the code, which is outside of its current scope. I'd be happy to look at any pull requests for this kind of functionality, but I don't have time to add anything like this myself right now. Sorry!

**Comment by satazor** [comment]
I understand and respect, thanks anyway!
