### ISSUE TITLE
Aligning by words

### ISSUE THREAD

**Issue by GerritSommer** [jarod2d/sublime_valign#41]
Hi,
I am trying to align by a keyword `from`
 like:
```javascript
import entities from 'specifier';
import ent from 'specifier';
```
becoming:
```javascript
import entities from 'specifier';
import ent      from 'specifier';
```
I created a a settings file:
Library/Application Support/Sublime Text 3/Packages/VAlign/VAlign.sublime-settings
and added:
````json
{
  "alignment_chars": [
    {
      "char":        "from",
      "alignment":   "right",
      "left_space":  true,
      "right_space": true,
      "prefixes":    []
    }
  ]
}
````
I am not very into python, but I didn't see in the VAlign.py, why it shouldn't work. But even editing it directly into the cloned package wasn't successful. If someone could point me to right direction, I'd be very happy.

PS: Love the plugin. A proper Indentation helps alot against headaches.

**Comment by GerritSommer** [comment]
Ok, I think I found it out, after looking abit into RegExes in python.
If anyone is interested I could make a PR, but generally, you just have to replace the escaping of the chars in the regexes.

from:
````python
re.search("\\" + prefix + alignment_char["char"], line_string):
````
to:
````python
re.search(re.escape(prefix) + re.escape( alignment_char["char"]), line_string):
````

From what I read, this shouldn't have side effects, but allows to escape strings as well as special characters.

Indentation working:                    check!
First time working with python:   check!

**Comment by jarod2d** [comment]
Nice work, I'm glad you figured it out! This plugin is the only time I've worked in Python as well as you might be able to tell 😅

I'd be happy to take a PR with this fix if you'd like to open one!

**Comment by GerritSommer** [comment]
Oh damn, just saw this. I will try to make a PR.
